merged_dataset_classes = ['Apple', 'Banana', 'Cabbage', 'Capsicum', 'Tomato', 'Beans', 'Carrot', 'Cucumber', 'Curli-flower', 'Orange', 'Tomatos -> Tomato', 'Asparagus', 'Avocado', 'Beef',
'Bell_pepper', 'Bento', 'Blueberries', 'Bottle', 'Bread', 'Broccoli', 'Butter', 'Can', 'Cauliflower', 'Cheese', 'Chicken', 'Chicken_breast', 'Chocolate',
'Coffee', 'Corn', 'Egg', 'Eggs -> Egg', 'Energy_drink', 'Fish', 'Flour', 'Garlic', 'Goat_cheese -> Cheese', 'Grapes', 'Grated_cheese -> Cheese', 'Green_beans -> Green beans', 'Ground_beef',
'Guacamole', 'Ham', 'Heavy_cream', 'Humus', 'Juice', 'Ketchup', 'Kothmari', 'Leek', 'Lemon', 'Lettuce', 'Lime', 'Mango', 'Marmelade', 'Mayonaise', 'Milk', 'Mushrooms',
'Mustard', 'Nuts', 'Onion', 'Pak_choi', 'Parsley', 'Peach', 'Pear', 'Pineapple', 'Plasticsaveholder', 'Pot', 'Potato', 'Potatoes -> Potato', 'Pudding', 'Red_cabbage',
'Red_grapes -> Grapes', 'Rice_ball', 'Salad', 'Sandwich', 'Sausage', 'Shrimp', 'Smoothie', 'Spinach', 'Spring_onion', 'Strawberries', 'Sugar', 'Sweet_potato', 'Tea_a',
'Tea_i', 'Tomato_sauce', 'Tortillas', 'Turkey', 'Watermelon', 'Yogurt', '-', 'Artichoke', 'Beetroot', 'Blackberries', 'Book', 'Brussel sprouts', 'Cantaloupe',
'Carrots -> Carrot', 'Cerealbox', 'Clementine', 'Detergent', 'Drinks', 'Eggplant', 'Galia', 'Honeydew', 'Meat', 'Mushroom', 'Nectarine -> Peach', 'Oranges -> Orange', 'Peas', 'Plum',
'Pomegranate', 'Raspberries', 'Sauce', 'Shallot', 'Squash', 'Strawberry', 'Sweetcorn -> Corn', 'Tofu', 'Tomatoes -> Tomato', 'Zucchini -> Courgette', 'Apples -> Apple', 'Aubergine -> Eggplant', 'Bacon', 'Bananas -> Banana',
'Bazlama', 'Chocolate chips', 'Courgettes -> Courgette', 'Cream', 'Cream cheese', 'Dates', 'Ginger', 'Green beans', 'Green bell pepper -> Pepper', 'Green chilies -> Chilli', 'Lemons -> Lemon', 'Mineral water',
'Olive', 'Olives', 'Peppers -> Pepper', 'Red bell pepper -> Pepper', 'Red grapes -> Grapes', 'Red onion -> Onion', 'Salami', 'Spring onion', 'Tomato paste', 'Yellow bell pepper -> Pepper', 'Yoghurt', 'Banana_wb', 'Blackberry',
'Raspberry', 'Lemon_wb', 'Grapes_wb', 'Tomato_wb -> Tomato', 'Apple_wb -> Apple', 'Chilli_wb -> Chilli', 'Chilli']

merged2_classes = ['Potato', 'Cucumber', 'Almond', 'Carrot', 'Orange', 'Kiwi', 'Eggplant', 'Watermelon', 'Pineapple', 'Broccoli', 'Egg', 'Garlic', 'Cauliflower', 'Tomato_wob -> Tomato',
'Lemon_wob -> Lemon', 'Grapes_wob -> Grapes', 'Apple_wob -> Apple', 'Celery', 'Zucchina -> Courgette', 'Pepper', 'Banana_wob -> Banana', 'Onion', 'Chilli_wob -> Chilli', 'Pear',
'Chilli_wb -> Chilli', 'Tomato_wb -> Tomato', 'Apple_wb -> Apple', 'Grapes_wb -> Grapes', 'Banana_wb -> Banana', 'Lemon_wb -> Lemon', 'Avocado', 'Raspberry', 'Blackberry']

hardcoded_tot_classes = ['Apple', 'Banana', 'Cabbage', 'Tomato', 'Beans', 'Carrot', 'Cucumber', 'Cauliflower', 'Orange', 'Asparagus', 'Avocado',
'Blueberries', 'Broccoli', 'Butter', 'Cheese', 'Corn', 'Egg', 'Garlic', 'Grapes', 'Lemon', 'Lettuce', 'Lime', 'Mango',
'Nuts', 'Onion', 'Peach', 'Pear', 'Pineapple', 'Potato', 'Salad', 'Spinach', 'Strawberries', 'Watermelon', 'Artichoke', 'Blackberries', 'Brussel sprouts',
'Clementine', 'Eggplant', 'Peas', 'Plum', 'Pomegranate', 'Raspberries', 'Strawberry', 'Courgettes', 'Ginger', 'Green beans',
'Olive', 'Blackberry', 'Raspberry', 'Chilli', 'Almond', 'Kiwi', 'Celery', 'Pepper']

new_to_old_label = {
    'Apple': ['Apple', 'Apples', 'Apple_wb', 'Apple_wob', 'Apple_wb'],
    'Banana': ['Banana', 'Bananas', 'Banana_wob', 'Banana_wb'],
    'Cabbage': ['Cabbage'],
    'Tomato': ['Tomato', 'Tomatos', 'Tomatoes', 'Tomato_wb', 'Tomato_wob','Tomato_wb'],
    'Beans': ['Beans'],
    'Carrot': ['Carrot', 'Carrots', 'Carrot'],
    'Cucumber': ['Cucumber', 'Cucumber'],
    'Orange': ['Orange', 'Oranges', 'Orange'],
    'Asparagus': ['Asparagus'],
    'Avocado': ['Avocado', 'Avocado'],
    'Blueberries': ['Blueberries'],
    'Broccoli': ['Broccoli', 'Broccoli'],
    'Butter': ['Butter'],
    'Cauliflower': ['Cauliflower', 'Cauliflower'],
    'Cheese': ['Cheese', 'Goat_cheese', 'Grated_cheese'],
    'Corn': ['Corn', 'Sweetcorn'],
    'Egg': ['Egg', 'Eggs', 'Egg'],
    'Garlic': ['Garlic', 'Garlic'],
    'Grapes': ['Grapes', 'Red_grapes', 'Red grapes', 'Grapes_wob', 'Grapes_wb'],
    'Green beans': ['Green_beans', 'Green beans'],
    'Lemon': ['Lemon', 'Lemons', 'Lemon_wob', 'Lemon_wb'],
    'Lettuce': ['Lettuce'],
    'Lime': ['Lime'],
    'Mango': ['Mango'],
    'Nuts': ['Nuts'],
    'Onion': ['Onion', 'Red onion', 'Onion'],
    'Peach': ['Peach', 'Nectarine'],
    'Pear': ['Pear', 'Pear'],
    'Pineapple': ['Pineapple', 'Pineapple'],
    'Potato': ['Potato', 'Potatoes', 'Potato'],
    'Salad': ['Salad'],
    'Spinach': ['Spinach'],
    'Strawberries': ['Strawberries'],
    'Watermelon': ['Watermelon', 'Watermelon'],
    'Artichoke': ['Artichoke'],
    'Blackberries': ['Blackberries'],
    'Brussel sprouts': ['Brussel sprouts'],
    'Clementine': ['Clementine'],
    'Eggplant': ['Eggplant', 'Aubergine', 'Eggplant'],
    'Peas': ['Peas'],
    'Plum': ['Plum'],
    'Pomegranate': ['Pomegranate'],
    'Raspberries': ['Raspberries'],
    'Strawberry': ['Strawberry'],
    'Ginger': ['Ginger'],
    'Pepper': ['Green bell pepper', 'Peppers', 'Red bell pepper', 'Yellow bell pepper', 'Pepper'],
    'Chilli': ['Green chilies', 'Chilli_wb', 'Chilli', 'Chilli_wob', 'Chilli_wb'],
    'Olive': ['Olive'],
    'Blackberry': ['Blackberry', 'Blackberry'],
    'Raspberry': ['Raspberry', 'Raspberry'],
    'Almond': ['Almond'],
    'Kiwi': ['Kiwi'],
    'Celery': ['Celery']
}

label_to_name = {
    'Apple': 'Apple', 
    'Banana': 'Banana', 
    'Cabbage': 'Cabbage', 
    'Capsicum': None, 
    'Tomato': 'Tomato', 
    'Beans': 'Beans', 
    'Carrot': 'Carrot', 
    'Cucumber': 'Cucumber',
    'Curli-flower': None, 
    'Orange': 'Orange', 
    'Tomatos': 'Tomato', 
    'Asparagus': 'Asparagus', 
    'Avocado': 'Avocado', 
    'Beef': None, 
    'Bell_pepper': None, 
    'Bento': None, 
    'Blueberries': 'Blueberries', 
    'Bottle': None, 
    'Bread': None, 
    'Broccoli': 'Broccoli', 
    'Butter': 'Butter', 
    'Can': None, 
    'Cauliflower': 'Cauliflower', 
    'Cheese': 'Cheese', 
    'Chicken': None, 
    'Chicken_breast': None, 
    'Chocolate': None, 
    'Coffee': None, 
    'Corn': 'Corn', 
    'Egg': 'Egg', 
    'Eggs': 'Egg', 
    'Energy_drink': None, 
    'Fish': None, 
    'Flour': None, 
    'Garlic': 'Garlic', 
    'Goat_cheese': 'Cheese', 
    'Grapes': 'Grapes', 
    'Grated_cheese': 'Cheese', 
    'Green_beans': 'Green beans', 
    'Ground_beef': None, 
    'Guacamole': None, 
    'Ham': None, 
    'Heavy_cream': None, 
    'Humus': None, 
    'Juice': None, 
    'Ketchup': None, 
    'Kothmari': None, 
    'Leek': None, 
    'Lemon': 'Lemon', 
    'Lettuce': 'Lettuce', 
    'Lime': 'Lime', 
    'Mango': 'Mango', 
    'Marmelade': None, 
    'Mayonaise': None, 
    'Milk': None, 
    'Mushrooms': None, 
    'Mustard': None, 
    'Nuts': 'Nuts', 
    'Onion': 'Onion', 
    'Pak_choi': None, 
    'Parsley': None, 
    'Peach': 'Peach', 
    'Pear': 'Pear', 
    'Pineapple': 'Pineapple', 
    'Plasticsaveholder': None, 
    'Pot': None, 
    'Potato': 'Potato', 
    'Potatoes': 'Potato', 
    'Pudding': None, 
    'Red_cabbage': None, 
    'Red_grapes': 'Grapes', 
    'Rice_ball': None, 
    'Salad': 'Salad', 
    'Sandwich': None, 
    'Sausage': None, 
    'Shrimp': None, 
    'Smoothie': None, 
    'Spinach': 'Spinach', 
    'Spring_onion': None, 
    'Strawberries': 'Strawberries', 
    'Sugar': None, 
    'Sweet_potato': None, 
    'Tea_a': None, 
    'Tea_i': None, 
    'Tomato_sauce': None, 
    'Tortillas': None, 
    'Turkey': None, 
    'Watermelon': 'Watermelon', 
    'Yogurt': None, 
    '-': None, 
    'Artichoke': 'Artichoke', 
    'Beetroot': None, 
    'Blackberries': 'Blackberries', 
    'Book': None, 
    'Brussel sprouts': 'Brussel sprouts', 
    'Cantaloupe': None, 
    'Carrots': 'Carrot', 
    'Cerealbox': None, 
    'Clementine': 'Clementine', 
    'Detergent': None, 
    'Drinks': None, 
    'Eggplant': 'Eggplant', 
    'Galia': None, 
    'Honeydew': None, 
    'Meat': None, 
    'Mushroom': None, 
    'Nectarine': 'Peach', 
    'Oranges': 'Orange', 
    'Peas': 'Peas', 
    'Plum': 'Plum', 
    'Pomegranate': 'Pomegranate', 
    'Raspberries': 'Raspberries', 
    'Sauce': None, 
    'Shallot': None, 
    'Squash': None, 
    'Strawberry': 'Strawberry', 
    'Sweetcorn': 'Corn', 
    'Tofu': None, 
    'Tomatoes': 'Tomato', 
    'Zucchini': None, 
    'Apples': 'Apple', 
    'Aubergine': 'Eggplant', 
    'Bacon': None, 
    'Bananas': 'Banana', 
    'Bazlama': None, 
    'Chocolate chips': None, 
    'Courgettes': None, 
    'Cream': None, 
    'Cream cheese': None, 
    'Dates': None, 
    'Ginger': 'Ginger', 
    'Green beans': 'Green beans', 
    'Green bell pepper': 'Pepper', 
    'Green chilies': 'Chilli', 
    'Lemons': 'Lemon', 
    'Mineral water': None, 
    'Olive': 'Olive', 
    'Olives': None, 
    'Peppers': 'Pepper', 
    'Red bell pepper': 'Pepper', 
    'Red grapes': 'Grapes', 
    'Red onion': 'Onion', 
    'Salami': None, 
    'Spring onion': None, 
    'Tomato paste': None, 
    'Yellow bell pepper': 'Pepper', 
    'Yoghurt': None, 
    'Banana_wb': 'Banana', 
    'Blackberry': 'Blackberry', 
    'Raspberry': 'Raspberry', 
    'Lemon_wb': 'Lemon', 
    'Grapes_wb': 'Grapes', 
    'Tomato_wb': 'Tomato', 
    'Apple_wb': 'Apple', 
    'Chilli_wb': 'Chilli', 
    'Chilli': 'Chilli', 
    'Almond': 'Almond', 
    'Kiwi': 'Kiwi', 
    'Tomato_wob': 'Tomato', 
    'Lemon_wob': 'Lemon', 
    'Grapes_wob': 'Grapes', 
    'Apple_wob': 'Apple', 
    'Celery': 'Celery', 
    'Zucchina': None, 
    'Pepper': 'Pepper', 
    'Banana_wob': 'Banana', 
    'Chilli_wob': 'Chilli'
}